# Generated by Django 2.2.4 on 2019-08-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ManyToManyField(related_name='companies', to='jobboard.Industry'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobboard.Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('0', 'Junior'), ('1', 'Mid Level'), ('2', 'Senior'), ('3', 'Executive')], default=1, max_length=225),
        ),
    ]
