# Generated by Django 2.2.4 on 2019-08-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0003_remove_industry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
